name: Build and publish the image

on:
  push:
    branches: [ master ]
    paths: ['Dockerfile', '*.js', 'package.json']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: https://hub.docker.com/
      DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/riscv64
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      
      - name: Cache Docker layers
        uses: actions/cache@v3.0.10
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: boris1993/ddns-bridge:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
